import p00, p01, p02, p03, p04, p05, p06, p07, p08, p09, p10

if __name__ == "__main__":
    print("=== Задание 0 ===")
    p00.run()
    print("\n=== Задание 1 ===")
    p01.run()
    print("\n=== Задание 2 ===")
    p02.run()
    print("\n=== Задание 3 ===")
    p03.run()
    print("\n=== Задание 4 ===")
    p04.run()
    print("\n=== Задание 5 ===")
    p05.run()
    print("\n=== Задание 6 ===")
    p06.run()
    print("\n=== Задание 7 ===")
    p07.run()
    print("\n=== Задание 8 ===")
    p08.run()
    print("\n=== Задание 9 ===")
    p09.run()
    print("\n=== Задание 10 ===")
    p10.run()
